### ISSUE TITLE
Add cache for generated images

### ISSUE THREAD

**Issue by miloskroulik** [kartena/printlet#9]
If I read the server,js correctly, there's currently no caching for generated images. Do you think it would be useful, for example for large Geojson geometries?

**Comment by icetan** [comment]
Caching results is a bit out of scope for what `server.js` is meant to be used for. It is mainly an integration example.

What is missing from the `printlet` lib though is an API for defining how to cache tile images. Right now each tile image is always requested even though it has been used before. This might be fine as a default behaviour depending on how you are using it. The simplest application is to use it as a proxy for an already cached tile service like MapProxy and you might even run them on the same machine which would only make another cache redundant.
